language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
    - os: linux
      r_github_packages: r-lib/xml2
    - os: osx
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode11.3
    - os: osx
      env:
        - PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
      before_install:
        - brew install libxml2
    - os: osx
      osx_image: xcode10.1
      disable_homebrew: true
      before_script: git config --global --unset protocol.version

addons:
  apt:
    packages:
      - libxslt1-dev
