language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
    - os: osx
      before_install:
        - brew install libxml2
        - brew link --force libxml2

addons:
  apt:
    packages:
      - libxslt1-dev
      - valgrind
