language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode9.1
      before_install:
        - brew install libxml2
        - brew link --force libxml2
    - os: osx
      osx_image: xcode7.3

addons:
  apt:
    packages:
      - libxslt1-dev
      - valgrind

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
