language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
    - os: linux
      r_github_packages: r-lib/xml2
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode11.4
    - os: osx
      env:
        - PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
      before_install:
        - brew install libxml2
    - r: 3.6
      os: osx
      osx_image: xcode7.3
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf
      disable_homebrew: true

addons:
  apt:
    packages:
      - libxslt1-dev
