language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8
      latex: false
      before_install:
        - cp /usr/bin/xml2-config /usr/local/bin/xml2-config
        - sed -i.bak 's#prefix=$(xcrun -show-sdk-path)/usr#prefix=/usr#' /usr/local/bin/xml2-config
    - os: osx
      osx_image: xcode8
      before_install:
        - brew install libxml2
        - brew link --force libxml2
      latex: false
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true

addons:
  apt:
    packages:
      - libxml2-dev
      - valgrind

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
